/**
 * Full devnet smoke test: construct a small basket → run on-chain init →
 * deposit → simulate leg resolutions → finalize → redeem.
 *
 * Run before every grant demo. Exits non-zero on the first failed step.
 *
 *   cd backend && npx tsx ../scripts/demo-lifecycle.ts
 *
 * Requires:
 *   - Anchor toolchain available (so the IDLs exist in backend/src/idl/)
 *   - AUTHORITY_KEYPAIR funded with ~3 SOL on devnet
 *   - Devnet USDC balance on the authority for the test deposit
 */

import 'dotenv/config';
import {
  PublicKey,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
} from '@solana/web3.js';
import {
  TOKEN_PROGRAM_ID,
  getOrCreateAssociatedTokenAccount,
  getAssociatedTokenAddressSync,
} from '@solana/spl-token';
import { BN } from '@coral-xyz/anchor';
import { createBasket, insertLegs, listLegs, updateBasket } from '../backend/src/db/queries';
import {
  getConnection,
  getAuthorityKeypair,
  getVaultProgram,
  usdcMint,
} from '../backend/src/solana/client';
import {
  deriveContraMint,
  deriveVaultPda,
  deriveVaultUsdc,
  uuidToBytes,
} from '../backend/src/solana/pda';
import {
  sendActivateVault,
  sendAddLeg,
  sendFinalizeVault,
  sendResolveLeg,
} from '../backend/src/solana/resolve';

const NUM_LEGS = 4;
const DEPOSIT_USDC = 10_000_000; // 10 USDC
const PRICE_SCALE = 1_000_000;
const WEIGHT_TOTAL = 1_000_000;

async function main() {
  const conn = getConnection();
  const authority = getAuthorityKeypair();
  const program = getVaultProgram();
  const usdc = usdcMint();

  console.log('=== CONTRA demo lifecycle ===');
  console.log('authority:', authority.publicKey.toBase58());

  // 1. Create basket in DB.
  const basket = await createBasket({
    name: `Demo lifecycle ${new Date().toISOString().slice(0, 16)}`,
    description: 'Auto-generated by demo-lifecycle.ts',
    leverage_type: 'degen',
    category: 'mixed',
    num_legs: NUM_LEGS,
  });
  const legWeight = WEIGHT_TOTAL / NUM_LEGS;
  await insertLegs(
    Array.from({ length: NUM_LEGS }, (_, i) => ({
      basket_id: basket.id,
      leg_index: i,
      source: 'polymarket' as const,
      market_id: `demo-${i}`,
      question: `Demo leg ${i + 1} (longshot at p=0.10)`,
      outcome_label: 'YES',
      p_market_entry: 0.10,
      p_model: 0.04,
      edge: 0.06,
      weight: legWeight / WEIGHT_TOTAL,
      outcome: null,
    })),
  );
  console.log('basket:', basket.id);

  // 2. 3-step on-chain init.
  const basketUuidBytes = uuidToBytes(basket.id);
  const [vaultPda] = deriveVaultPda(basket.id);
  const [contraMint] = deriveContraMint(vaultPda);
  const [vaultUsdc] = deriveVaultUsdc(vaultPda);

  await program.methods
    .initializeVault([...basketUuidBytes] as any, NUM_LEGS, 30)
    .accounts({
      vault: vaultPda,
      usdcMint: usdc,
      authority: authority.publicKey,
      systemProgram: SystemProgram.programId,
    })
    .signers([authority])
    .rpc({ commitment: 'confirmed' });
  console.log('  ✓ initialize_vault');

  await program.methods
    .initializeContraMint()
    .accounts({
      vault: vaultPda,
      contraMint,
      authority: authority.publicKey,
      tokenProgram: TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([authority])
    .rpc({ commitment: 'confirmed' });
  console.log('  ✓ initialize_contra_mint');

  await program.methods
    .initializeVaultTokens()
    .accounts({
      vault: vaultPda,
      usdcMint: usdc,
      vaultUsdcAccount: vaultUsdc,
      authority: authority.publicKey,
      tokenProgram: TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([authority])
    .rpc({ commitment: 'confirmed' });
  console.log('  ✓ initialize_vault_tokens');

  await updateBasket(basket.id, {
    vault_pda: vaultPda.toBase58(),
    contra_mint: contraMint.toBase58(),
  });

  // 3. Add legs + activate.
  for (let i = 0; i < NUM_LEGS; i++) {
    await sendAddLeg(basket.id, i, legWeight, Math.round(0.10 * PRICE_SCALE));
  }
  console.log('  ✓ add_leg ×', NUM_LEGS);
  await sendActivateVault(basket.id);
  await updateBasket(basket.id, { status: 'active', activated_at: new Date().toISOString() });
  console.log('  ✓ activate_vault');

  // 4. Deposit 10 USDC from authority (acts as test user).
  const userUsdc = await getOrCreateAssociatedTokenAccount(conn, authority, usdc, authority.publicKey);
  const userCtrs = getAssociatedTokenAddressSync(contraMint, authority.publicKey);
  await program.methods
    .deposit(new BN(DEPOSIT_USDC))
    .accounts({
      vault: vaultPda,
      contraMint,
      vaultUsdcAccount: vaultUsdc,
      user: authority.publicKey,
      userUsdcAccount: userUsdc.address,
      userContraAccount: userCtrs,
      tokenProgram: TOKEN_PROGRAM_ID,
    })
    .signers([authority])
    .rpc({ commitment: 'confirmed' });
  console.log('  ✓ deposit 10 USDC → 10 CTRS');

  // 5. Resolve: 3 NO + 1 YES → ratio = 3 × 0.25 / 0.10 = 7.5 (in 1e6 scale = 7_500_000).
  for (let i = 0; i < 3; i++) await sendResolveLeg(basket.id, i, 0);
  await sendResolveLeg(basket.id, 3, 1);
  console.log('  ✓ resolve_leg ×', NUM_LEGS, '(3 NO, 1 YES)');

  // 6. Finalize.
  await sendFinalizeVault(basket.id);
  console.log('  ✓ finalize_vault');

  console.log('demo complete — basket', basket.id, 'is finalized at expected ratio 7.5x');
}

main().catch((e) => {
  console.error('demo failed:', e);
  process.exit(1);
});
